### ISSUE TITLE
Update version of recoil

### ISSUE THREAD

**Issue by shtbik** [ulises-jeremias/recoil-devtools#32]
The [recoil version](https://github.com/facebookexperimental/Recoil/releases/tag/0.4.0) has been released recently and now, if you have `npm@^7.0.0` and `recoil@^0.4.0`, `npm install` will throw the error:
```
Found: recoil@0.4.0
npm ERR! node_modules/recoil
npm ERR!   recoil@"^0.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer recoil@"^0.2.0" from recoil-devtools-logger@0.2.0
npm ERR! node_modules/recoil-devtools-logger
npm ERR!   dev recoil-devtools-logger@"^0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```
I ask to update the recoil [peerDependency](https://github.com/ulises-jeremias/recoil-devtools/blob/master/packages/recoil-devtools-logger/package.json#L24) for the `recoil-devtools-logger` package and release a new version of it. I guess there shouldn't be breaking changes.

As a workaround, I can use `npm install` with `--force`, or `--legacy-peer-deps` flags.

**Enviroment**
`npm -v` - `7.20.6`
`node -v` - `v12.22.2`
`cat /etc/os-release` -
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```
The library which you've created is beautiful and works as expected 🥇

**Comment by ulises-jeremias** [comment]
great! thanks for opening this issue @shtbik !
I'll create a new release today 👌🏻

**Comment by ulises-jeremias** [comment]
@shtbik   I just updated the peer depepdency for all recoil devtools and also the one existing on the demo with recoil version ^0.4.0. The new versions are:

```json
"recoil-devtools": "^0.4.0",
"recoil-devtools-dock": "^0.4.0",
"recoil-devtools-log-monitor": "^0.4.0",
"recoil-devtools-logger": "^0.4.0",
```

Let me know if you see any issue!

**Comment by ulises-jeremias** [comment]
I'll close the issue once you can confirm the problem was solved 👌🏻

**Comment by shtbik** [comment]
I confirm, `recoil-devtools-logger` works as expected
